baseURL = "https://www.aspii.xyz"
languageCode = "en-us"
title = "ASPII.xyz"
theme="archie"
copyright = "© Autonot"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 5

themeDir = "themes"



enableEmoji = true
enableRobotsTXT = true

[taxonomies]
	tag = "tags"

[params]
	favicon = "https://img.icons8.com/stickers/344/x--v2.png"
	mode="auto"
	useCDN=true
	subtitle = "Helloooo welcome to my website thing."
	description = "This is a semi-decent website I made. You'll find a few miscellaneous things here :)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/autonot"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/autonot2025/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "FAQs"
url = "/faqs"
weight = 4

[[menu.main]]
name = "Games"
url = "/games"
weight = 5
